config/routes.rb
Rails.application.routes.draw do
  
  resources :advertising_orders, only: [:new, :create, :show]

end

app/models/advertising_order.rb
class AdvertisingOrder < ApplicationRecord
    mount_uploader :ad_image, AdImageUploader
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/advertising_orders_controller.rb
class AdvertisingOrdersController < ApplicationController

    def new
        @advertising_order = AdvertisingOrder.new
    end

    def create
        @advertising_order = AdvertisingOrder.new(advertising_order_params)
        @advertising_order.price = (@advertising_order.ad_height * @advertising_order.ad_width) * 80
        

        if @advertising_order.save
          redirect_to @advertising_order, notice: 'Advertising order was successfully created.'
        else
          render :new
        end
    end

    def show
        @advertising_order = AdvertisingOrder.find(params[:id])
    end


    private

    def advertising_order_params
      params.require(:advertising_order).permit(:ad_width, :ad_height, :comment, :ad_topic, :ad_image, :number_of_inserts)
    end
end
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/advertising_orders/new.html.erb
<%= image_tag("2d956d510853e68854816ab7aea58582.jpeg", alt: "щось там", class: "background-photo") %>

<div class = "container">
  <div class = "order-content">

    <h2>Замовити рекламний простір</h2>
    <%= form_with(model: @advertising_order, url: advertising_orders_path, class: "form", local: true, multipart: true) do |form| %>

        <div class="form-section">
          <%= form.label "Тема реклами:", class: "label content__label" %>
          <%= form.text_field :ad_topic%>
        </div>

        <div class="form-section">
        <%= form.label "Кількість повторень:", class: "label content__label"%>
        <%= form.text_field :number_of_inserts, class: "numerical-text-field"%>
        </div>

        <div class="form-section-horizontally">

          <div class="form-section-horizontally">
            <div class="form-section">
              <%= form.label "Ширина простору см.", class: "label content__label" %>
              <%= form.text_field :ad_width, class: "numerical-text-field", id: "advertising_order_ad_width" %>
            </div>

            <div class="form-section">
              <%= form.label "Висота простору, см.", class: "label content__label" %>
              <%= form.text_field :ad_height, class: "numerical-text-field", id: "advertising_order_ad_height" %>
            </div>
          </div>

        </div>

        <div class="form-coment-section">
          <%= form.label "Коментар до замовлення:", class: "label content__label" %>
          <%= form.text_area :comment, class: "comment_text_area" %>
        </div>

        <div class="form-section">
          <div class="file-input-wrapper">
            <%= form.label "Прикріпити файл до замовлення:", class: "label content__label" %>
            
            <%= form.file_field :ad_image, class: "file-input" %>
            <%= form.label :ad_image, "Файл", class: "label content__label file-label" %>
          </div>
        </div>


        <div class="form-section price-form-section">
          <%= form.label "Приблизна вартість замовлення:", class: "label content__label" %>
          <div class = "price" id="price-display">0 грн</div>
        </div>
      
        <div >
          <%= form.submit "Надіслати замовлення", class: "submit-button" %>
        </div>
    <% end %>
      
  </div>

</div>


<script>
  document.addEventListener('DOMContentLoaded', function() {
    // Отримати елементи форми
    const widthField = document.getElementById('advertising_order_ad_width');
    const heightField = document.getElementById('advertising_order_ad_height');
    const priceDisplay = document.getElementById('price-display');

    // Функція для вираховування вартості та відображення результату
    function calculatePrice() {
      const width = parseFloat(widthField.value) || 0;
      const height = parseFloat(heightField.value) || 0;

      // Множимо ширину на висоту, можна застосувати свій розрахунок
      const price = width * height *80;

      // Відображення результату на сторінці
      priceDisplay.textContent = `${price} грн`;
    }

    // Викликати функцію при введенні користувача
    widthField.addEventListener('input', calculatePrice);
    heightField.addEventListener('input', calculatePrice);
  });

</script>

<script>
  document.addEventListener('DOMContentLoaded', function() {
    const form = document.querySelector('.form');

    form.addEventListener('submit', function(event) {
      if (!validateForm()) {
        event.preventDefault();
      }
    });

    function validateForm() {
      let isValid = true;

      // Очистка попередніх помилок
      clearErrors();

      // Перевірка на заповненість та правильність числових полів
      const adWidthInput = document.getElementById('advertising_order_ad_width');
      const adHeightInput = document.getElementById('advertising_order_ad_height');
      const numberOfInsertsInput = document.getElementById('advertising_order_number_of_inserts');
      const fileInput = document.getElementById('advertising_order_ad_image'); // Замініть на відповідний ID для файлового поля

      const adWidth = parseFloat(adWidthInput.value);
      const adHeight = parseFloat(adHeightInput.value);
      const numberOfInserts = parseInt(numberOfInsertsInput.value);

      // Перевірка чи всі поля заповнені
      if (!adWidthInput.value || !adHeightInput.value || !numberOfInsertsInput.value || !fileInput.value) {
        alert('Будь ласка, заповніть всі поля та прикріпіть файл.');
        isValid = false;
      } else {
        // Перевірка на правильність числових полів
        if (isNaN(numberOfInserts)) {
          displayError(numberOfInsertsInput);
          isValid = false;
        } else if (isNaN(adWidth)) {
          displayError(adWidthInput);
          isValid = false;
        } else if (isNaN(adHeight)) {
          displayError(adHeightInput);
          isValid = false;
        }
      }

      return isValid;
    }

    function displayError(inputElement) {
      inputElement.classList.add('error-border');
    }

    function clearErrors() {
      const inputs = document.querySelectorAll('.numerical-text-field');
      inputs.forEach(input => input.classList.remove('error-border'));
    }
  });
</script>

app/views/advertising_orders/show.html.erb
<h1>Advertising Order Details</h1>

<p><strong>Width:</strong> <%= @advertising_order.ad_width %></p>
<p><strong>Height:</strong> <%= @advertising_order.ad_height %></p>
<p><strong>Comment:</strong> <%= @advertising_order.comment %></p>
<p><strong>Topic:</strong> <%= @advertising_order.ad_topic %></p>
<p><strong>Image:</strong> <%= image_tag @advertising_order.ad_image.url %> <!-- використовуйте image_tag для відображення зображення --></p>
<!-- Додайте інші деталі, які вам потрібні -->

<%= link_to 'Back', advertising_orders_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrintHUB</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    
    <div class = "topbar">
      <div class = "top-line"></div>

        <div class="container">
          <div class="header">

            <div class="logo header__logo">PrintHUB</div>
          
            <div class="right-bar">
              <div class="user-name header__user-name">User name</div>

              <div class="points header__points">Бонусні бали: 112</div>

            </div> 
            <div class="menu header__menu"><%= image_tag("menu.png", alt: "Меню", class: "menu_img") %></div>  

          </div>
        </div>
      </div>
    </div>

    <%= yield %>
    
    <div class="foot-linr">
      <div class = "footer">
        <div class="logo footer__logo">PrintHUB</div>

        <div class="text footer__text">Залишайтеся на зв'язку. Звертайтесь до нас будь-яким зручним для вас способом:</div>

        <div class="list-field">
          
          <div class="list">+380-96-566-43-33</div>
          <div class="list">instagram/_serhij_</div>
          <div class="list">serhiy90@gmail.com</div>
          <div class="list">Івано-Франківськ вул. Залізнична б.11</div>
        
        </div>


      </div>
    </div>
  </body>
</html>